#!/usr/bin/env python2

import argparse
import json
import os
import urllib2
import urllib
import sys

from subprocess import Popen, PIPE

CONFIG_FILE = '.refpasterc'
CONFIG_PATH = os.path.join(os.path.expanduser('~'), CONFIG_FILE)

def get_ext(path):
    name, ext = os.path.splitext(path)
    return ext

def save_in_clipboard(string):
    # credits to github.com/Raynes/rapture
    if sys.platform == 'darwin':
        cmd = 'pbcopy'
    elif 'linux' in sys.platform:
        cmd = 'xclip -selection clipboard'
    else:
        raise NotImplementedError("Platform not supported.")

    p = Popen([cmd], stdin=PIPE)
    p.communicate(input=string)

def sanity_check(args):
    if args.username and not args.token:
        print "Token not provided (--token)."
        sys.exit(1)

def extract_creds():
    try:
        with open(CONFIG_PATH, 'r') as f:
            userdata = json.load(f)
            if 'username' not in userdata and 'token' not in userdata:
                print "Need both username and token in config file, ignoring it."
                return None
            return userdata
    except IOError:
        pass
    except ValueError:
        print "Malformed config file, ignoring it."
    return None

def main():
    parser = argparse.ArgumentParser(description="Paste to http://www.refheap.com.")
    parser.add_argument('path',
                        nargs='?', default=None,
                        help="Path for file to paste.")
    parser.add_argument('--language', '-l',
                        dest='language', default=None,
                        help="Language for syntax highlighting. You can omit \
                              this and will try to infer from the file ext.")
    parser.add_argument('--private', '-p',
                        dest='private', default=False,
                        help="Whether to make the paste private.")
    parser.add_argument('--no-clipboard', '-n', action='store_true',
                        dest='no_clipboard', default=False,
                        help="If you don't want the URL in the clipboard.")
    parser.add_argument('--username', '-u',
                        dest='username', default=None,
                        help="Username to associate paste with. Needs token!")
    parser.add_argument('--token', '-t',
                        dest='token', default=None,
                        help="Token to verify username.")
    parser.add_argument('--anonymous', '-a', action='store_true',
                        dest='anonymous', default=False,
                        help="Paste anonymously.")

    args = parser.parse_args()
    sanity_check(args)

    data = {}
    data['private'] = args.private

    if not args.anonymous:
        userdata = extract_creds()
        if userdata:
            data.update(userdata)

        if args.username:
            data['username'] = args.username
            data['token'] = args.token

    if args.path:
        with open(args.path, 'r') as f:
            data['contents'] = f.read()
        data['language'] = args.language if args.language else get_ext(args.path)
    else:
        data['contents'] = sys.stdin.read()
        data['language'] = args.language if args.language else 'Plain Text'

    req = None
    try:
        req = urllib2.urlopen("https://www.refheap.com/api/paste",
                              data=urllib.urlencode(data))
    except urllib2.HTTPError:
        print "Bad request. Wrong user & token, maybe?"
        sys.exit(1)

    response = json.loads(req.read())
    url = response['url']

    if args.no_clipboard:
        print "Pasted at %s." % url
    else:
        try:
            save_in_clipboard(url)
        except NotImplementedError:
            print "Don't know how to save to clipboard on your platform."
            print "Pasted at %s." % url
        except OSError:
            print "Had trouble with pasting to clipboard on your platform."
            print "Pasted at %s." % url
        else:
            print "Saved %s in your clipboard." % url


if __name__ == '__main__':
    main()
